[package]
name = "jqawk"
version = "0.1.0"
edition = "2018"
autotests = false

[[bin]]
name = "jqawk"
test = false

[[test]]
name = "tests"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.0"
atty = "0.2"