// Code generated by "stringer -type=TokenTag -linecomment"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Ident-2]
	_ = x[Str-3]
	_ = x[Regex-4]
	_ = x[Num-5]
	_ = x[Begin-6]
	_ = x[End-7]
	_ = x[BeginFile-8]
	_ = x[EndFile-9]
	_ = x[Print-10]
	_ = x[Function-11]
	_ = x[Return-12]
	_ = x[If-13]
	_ = x[Else-14]
	_ = x[For-15]
	_ = x[While-16]
	_ = x[In-17]
	_ = x[Match-18]
	_ = x[Break-19]
	_ = x[Continue-20]
	_ = x[Next-21]
	_ = x[Newline-22]
	_ = x[Exit-23]
	_ = x[Null-24]
	_ = x[Is-25]
	_ = x[Let-26]
	_ = x[Fn-27]
	_ = x[True-28]
	_ = x[False-29]
	_ = x[LCurly-30]
	_ = x[RCurly-31]
	_ = x[LSquare-32]
	_ = x[RSquare-33]
	_ = x[LParen-34]
	_ = x[RParen-35]
	_ = x[LessThan-36]
	_ = x[GreaterThan-37]
	_ = x[Dollar-38]
	_ = x[Comma-39]
	_ = x[Dot-40]
	_ = x[Equal-41]
	_ = x[EqualEqual-42]
	_ = x[BangEqual-43]
	_ = x[LessEqual-44]
	_ = x[GreaterEqual-45]
	_ = x[Colon-46]
	_ = x[SemiColon-47]
	_ = x[Plus-48]
	_ = x[Minus-49]
	_ = x[Multiply-50]
	_ = x[Power-51]
	_ = x[Divide-52]
	_ = x[PlusEqual-53]
	_ = x[MinusEqual-54]
	_ = x[MultiplyEqual-55]
	_ = x[DivideEqual-56]
	_ = x[Tilde-57]
	_ = x[BangTilde-58]
	_ = x[AmpAmp-59]
	_ = x[PipePipe-60]
	_ = x[Arrow-61]
	_ = x[Bang-62]
	_ = x[PlusPlus-63]
	_ = x[MinusMinus-64]
	_ = x[Percent-65]
	_ = x[Question-66]
}

const _TokenTag_name = "EOFErrorIdentStrRegexNumBeginEndBeginFileEndFilePrintFunctionReturnIfElseForWhileInMatchBreakContinueNextNewlineExitNullIsLetFntruefalse{}[]()<>$,.===!=<=>=:;+-***/+=-=*=/=~!~&&||=>!++--%?"

var _TokenTag_index = [...]uint8{0, 3, 8, 13, 16, 21, 24, 29, 32, 41, 48, 53, 61, 67, 69, 73, 76, 81, 83, 88, 93, 101, 105, 112, 116, 120, 122, 125, 127, 131, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 150, 152, 154, 156, 157, 158, 159, 160, 161, 163, 164, 166, 168, 170, 172, 173, 175, 177, 179, 181, 182, 184, 186, 187, 188}

func (i TokenTag) String() string {
	if i >= TokenTag(len(_TokenTag_index)-1) {
		return "TokenTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenTag_name[_TokenTag_index[i]:_TokenTag_index[i+1]]
}
