// Code generated by "stringer -type=TokenTag -linecomment"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Ident-2]
	_ = x[Str-3]
	_ = x[Regex-4]
	_ = x[Num-5]
	_ = x[Begin-6]
	_ = x[End-7]
	_ = x[Print-8]
	_ = x[Function-9]
	_ = x[Return-10]
	_ = x[If-11]
	_ = x[Else-12]
	_ = x[For-13]
	_ = x[While-14]
	_ = x[In-15]
	_ = x[Match-16]
	_ = x[Break-17]
	_ = x[Continue-18]
	_ = x[Next-19]
	_ = x[Newline-20]
	_ = x[Exit-21]
	_ = x[True-22]
	_ = x[False-23]
	_ = x[LCurly-24]
	_ = x[RCurly-25]
	_ = x[LSquare-26]
	_ = x[RSquare-27]
	_ = x[LParen-28]
	_ = x[RParen-29]
	_ = x[LessThan-30]
	_ = x[GreaterThan-31]
	_ = x[Dollar-32]
	_ = x[Comma-33]
	_ = x[Dot-34]
	_ = x[Equal-35]
	_ = x[EqualEqual-36]
	_ = x[BangEqual-37]
	_ = x[LessEqual-38]
	_ = x[GreaterEqual-39]
	_ = x[Colon-40]
	_ = x[SemiColon-41]
	_ = x[Plus-42]
	_ = x[Minus-43]
	_ = x[Multiply-44]
	_ = x[Divide-45]
	_ = x[PlusEqual-46]
	_ = x[MinusEqual-47]
	_ = x[MultiplyEqual-48]
	_ = x[DivideEqual-49]
	_ = x[Tilde-50]
	_ = x[BangTilde-51]
	_ = x[AmpAmp-52]
	_ = x[PipePipe-53]
	_ = x[Arrow-54]
	_ = x[Bang-55]
	_ = x[PlusPlus-56]
	_ = x[MinusMinus-57]
	_ = x[Percent-58]
}

const _TokenTag_name = "EOFErrorIdentStrRegexNumBeginEndPrintFunctionReturnIfElseForWhileInMatchBreakContinueNextNewlineExittruefalse{}[]()<>$,.===!=<=>=:;+-*/+=-=*=/=~!~&&||=>!++--%"

var _TokenTag_index = [...]uint8{0, 3, 8, 13, 16, 21, 24, 29, 32, 37, 45, 51, 53, 57, 60, 65, 67, 72, 77, 85, 89, 96, 100, 104, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 123, 125, 127, 129, 130, 131, 132, 133, 134, 135, 137, 139, 141, 143, 144, 146, 148, 150, 152, 153, 155, 157, 158}

func (i TokenTag) String() string {
	if i >= TokenTag(len(_TokenTag_index)-1) {
		return "TokenTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenTag_name[_TokenTag_index[i]:_TokenTag_index[i+1]]
}
