// Code generated by "stringer -type=TokenTag -linecomment"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[Ident-2]
	_ = x[Str-3]
	_ = x[Regex-4]
	_ = x[Num-5]
	_ = x[Begin-6]
	_ = x[End-7]
	_ = x[Print-8]
	_ = x[Function-9]
	_ = x[Return-10]
	_ = x[If-11]
	_ = x[Else-12]
	_ = x[For-13]
	_ = x[While-14]
	_ = x[In-15]
	_ = x[Match-16]
	_ = x[Break-17]
	_ = x[Continue-18]
	_ = x[True-19]
	_ = x[False-20]
	_ = x[LCurly-21]
	_ = x[RCurly-22]
	_ = x[LSquare-23]
	_ = x[RSquare-24]
	_ = x[LParen-25]
	_ = x[RParen-26]
	_ = x[LessThan-27]
	_ = x[GreaterThan-28]
	_ = x[Dollar-29]
	_ = x[Comma-30]
	_ = x[Dot-31]
	_ = x[Equal-32]
	_ = x[EqualEqual-33]
	_ = x[BangEqual-34]
	_ = x[LessEqual-35]
	_ = x[GreaterEqual-36]
	_ = x[Colon-37]
	_ = x[SemiColon-38]
	_ = x[Plus-39]
	_ = x[Minus-40]
	_ = x[Multiply-41]
	_ = x[Divide-42]
	_ = x[PlusEqual-43]
	_ = x[MinusEqual-44]
	_ = x[MultiplyEqual-45]
	_ = x[DivideEqual-46]
	_ = x[Tilde-47]
	_ = x[BangTilde-48]
	_ = x[AmpAmp-49]
	_ = x[PipePipe-50]
	_ = x[Arrow-51]
	_ = x[Bang-52]
	_ = x[PlusPlus-53]
	_ = x[MinusMinus-54]
	_ = x[Percent-55]
}

const _TokenTag_name = "EOFErrorIdentStrRegexNumBeginEndPrintFunctionReturnIfElseForWhileInMatchBreakContinuetruefalse{}[]()<>$,.===!=<=>=:;+-*/+=-=*=/=~!~&&||=>!++--%"

var _TokenTag_index = [...]uint8{0, 3, 8, 13, 16, 21, 24, 29, 32, 37, 45, 51, 53, 57, 60, 65, 67, 72, 77, 85, 89, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 108, 110, 112, 114, 115, 116, 117, 118, 119, 120, 122, 124, 126, 128, 129, 131, 133, 135, 137, 138, 140, 142, 143}

func (i TokenTag) String() string {
	if i >= TokenTag(len(_TokenTag_index)-1) {
		return "TokenTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenTag_name[_TokenTag_index[i]:_TokenTag_index[i+1]]
}
