name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: build
      run: go build -v .

    - name: test
      run: go test -v .
